use esm;
drop table AccountsTR;

create table AccountsTR (
    accountsTRId                   int not null primary key auto_increment,
	ID                             varchar(10) not null,
	MitgliedsNr                    varchar(10) not null,
        NeueMitgliedsNr                varchar(10),
	TrainerSeit                    date not null,
	TrainerBis                     date,
	Vorname                        varchar(64) not null,
	Nachname                       varchar(64) not null,
	Titel                          varchar(32),
	Adresszusatz                   varchar(32),
	Strasse                        varchar(64) not null,
	Ort                            varchar(64) not null,
	Countrycode                    char(2) not null,
	PLZ                            varchar(10) not null,
	TelefonPrivat                  varchar(32),
	TelefonDienst                  varchar(32),
	Mobiltelefon                   varchar(32),
	FAX                            varchar(32),
	EMail                          varchar(128),
	Geburtsdatum                   date not null,
	Geschlecht                     char(1) not null,
	KontoNr1                       varchar(20),
	BLZ1                           varchar(10),
	Bank1                          varchar(32),
	Kontoinhaber1                  varchar(32),
	KontoNr2                       varchar(20),
	BLZ2                           varchar(10),
	Bank2                          varchar(32),
	Kontoinhaber2                  varchar(32),
	ErsteingabeAm                  date not null,
	Kommentare                     text,
	Lizenz1                        varchar(32),
	LizenzNr1                      varchar(16),
	LizenzBis1                     date,
	LizenzZuschuss1                double precision,
	Lizenz2                        varchar(32),
	LizenzNr2                      varchar(16),
	LizenzBis2                     date,
	LizenzZuschuss2                double precision,
	Lizenz3                        varchar(32),
	LizenzNr3                      varchar(16),
	LizenzBis3                     date,
	LizenzZuschuss3                double precision,
	Lizenz4                        varchar(32),
	LizenzNr4                      varchar(16),
	LizenzBis4                     date,
	LizenzZuschuss4                double precision,
	Lizenz5                        varchar(32),
	LizenzNr5                      date,
	LizenzBis5                     date,
	LizenzZuschuss5                double precision,
	Lizenz6                        varchar(32),
	LizenzNr6                      date,
	LizenzBis6                     date,
	LizenzZuschuss6                double precision,
	Fortbildungen                  text,
        Honorar1                       varchar(32),
        HonorarBetrag1                 double precision,
        Honorar2                       varchar(32),
        HonorarBetrag2                 double precision,
        Honorar3                       varchar(32),
        HonorarBetrag3                 double precision,
        Honorar4                       varchar(32),
        HonorarBetrag4                 double precision,
        Honorar5                       varchar(32),
        HonorarBetrag5                 double precision,
        Honorar6                       varchar(32),
        HonorarBetrag6                 double precision,
	Training1                      varchar(32),
	TrainingOrt1                   varchar(32),
	TrainingTermin1                varchar(20),
	Training2                      varchar(32),
	TrainingOrt2                   varchar(32),
	TrainingTermin2                varchar(20),
	Training3                      varchar(32),
	TrainingOrt3                   varchar(32),
	TrainingTermin3                varchar(20),
	Training4                      varchar(32),
	TrainingOrt4                   varchar(32),
	TrainingTermin4                varchar(20),
	Training5                      varchar(32),
	TrainingOrt5                   varchar(32),
	TrainingTermin5                varchar(20),
	Training6                      varchar(32),
	TrainingOrt6                   varchar(32),
	TrainingTermin6                varchar(20),
	Training7                      varchar(32),
	TrainingOrt7                   varchar(32),
	TrainingTermin7                varchar(20),
	Training8                      varchar(32),
	TrainingOrt8                   varchar(32),
	TrainingTermin8                varchar(20),
	Training9                      varchar(32),
	TrainingOrt9                   varchar(32),
	TrainingTermin9                varchar(20),
	Training10                     varchar(32),
	TrainingOrt10                  varchar(32),
	TrainingTermin10               varchar(20),
	Fehlercode                     varchar(16),
	changedOn                      char(2) not null,
	changedBy                      varchar(32) not null,
	changedAt                      datetime not null
);
