drop table if exists AccountsVE;
create table AccountsVE (
    accountsVEId                   int not null primary key auto_increment,
	ID                             varchar(10) not null,
	VendorNr                       varchar(10) not null,
	Firma                          varchar(64) not null,
	Vorname                        varchar(64) not null,
	Nachname                       varchar(64) not null,
	Titel                          varchar(32),
	Adresszusatz                   varchar(32),
	Strasse                        varchar(64) not null,
	Ort                            varchar(64) not null,
	Countrycode                    char(2) not null,
	PLZ                            varchar(10) not null,
	TelefonPrivat                  varchar(32),
	TelefonDienst                  varchar(32),
	Mobiltelefon                   varchar(32),
	FAX                            varchar(32),
	EMail                          varchar(128),
	KontoNr1                       varchar(20),
	BLZ1                           varchar(10),
	Bank1                          varchar(32),
	Kontoinhaber1                  varchar(32),
	KontoNr2                       varchar(20),
	BLZ2                           varchar(10),
	Bank2                          varchar(32),
	Kontoinhaber2                  varchar(32),
	ErsteingabeAm                  date not null,
	Kommentare                     text,
	Fehlercode                     varchar(16),
	changedOn                      char(2) not null,
	changedBy                      varchar(32) not null,
	changedAt                      datetime not null
);
